# Generated by Django 2.2.7 on 2020-03-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_additional_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('add', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.user_details')),
            ],
        ),
    ]
