# Generated by Django 2.2.7 on 2020-03-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200330_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_additional_data',
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
