# Generated by Django 2.2.7 on 2020-03-30 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_user_additional_data_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_additional_data',
            name='add',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='testapp.user_details'),
        ),
    ]
